zabbix_export:
  version: '6.2'
  date: '2024-02-28T21:06:14Z'
  template_groups:
    -
      uuid: f7ad88c3be5c4d9791fa961d5442c83a
      name: 'Read Only'
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
  templates:
    -
      uuid: fb6a64d3449347c4bfbe87f0adb39a78
      template: 'Cosmos SDK node - prometheus'
      name: 'Cosmos SDK node - prometheus'
      groups:
        -
          name: 'Read Only'
        -
          name: Templates
      items:
        -
          uuid: 4da06eaa9a954ca0b33512f38f98dc9b
          name: 'Total Bonded Tokens'
          type: DEPENDENT
          key: chain.bonded.tokens
          delay: '0'
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_validators_power
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: tokens
        -
          uuid: 2405728801dc4ba790a1cda2bba1ece1
          name: go_threads
          type: DEPENDENT
          key: node.go_threads
          delay: '0'
          description: 'Number of OS threads created.'
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - go_threads
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: go_threads
        -
          uuid: c7f7677787fc459ba8c31b7cb5601761
          name: 'Node metrics'
          type: HTTP_AGENT
          key: prometheus.metrics.cometBFT
          delay: '{$PROM_UPDATE_INTERVAL}'
          history: '0'
          trends: '0'
          value_type: TEXT
          url: 'http://{HOST.DNS}:{$PORT_PROM}/metrics'
          tags:
            -
              tag: Application
              value: cometBFT
        -
          uuid: 9a28be92bb62458aa13bb3ac972bf0d4
          name: 'Block height'
          type: DEPENDENT
          key: tendermint.block.height
          delay: '0'
          history: 1d
          trends: '0'
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_height
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
        -
          uuid: b3f60cec98c041d28964bbd7581fc5c3
          name: 'Current Block Size (bytes)'
          type: DEPENDENT
          key: tendermint.block.size
          delay: '0'
          units: B
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_block_size_bytes
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: block_size
            -
              tag: Metric
              value: mempool
        -
          uuid: ff92c50615d84cda9450aef1dac36ed6
          name: tendermint_consensus_block_interval_seconds_count
          type: DEPENDENT
          key: tendermint.block.tendermint_consensus_block_interval_seconds_count
          delay: '0'
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_block_interval_seconds_count
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: consensus
        -
          uuid: d8e8adbd380049a281ccf2a54f60aafd
          name: tendermint_consensus_block_interval_seconds_sum
          type: DEPENDENT
          key: tendermint.block.tendermint_consensus_block_interval_seconds_sum
          delay: '0'
          units: ms
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_block_interval_seconds_sum
                - value
                - ''
            -
              type: JAVASCRIPT
              parameters:
                - |
                  var send = parseFloat(value);
                  val = Math.floor(send);
                  return val;
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: consensus
        -
          uuid: edf57f37c3864227a425eacd8c53c9c0
          name: tendermint_consensus_rounds
          type: DEPENDENT
          key: tendermint.block.tendermint_consensus_rounds
          delay: '0'
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_rounds
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: block
            -
              tag: Metric
              value: consensus
        -
          uuid: 96e756f7b14243dcbfdbc49126f81fec
          name: tendermint_state_block_processing_time_count
          type: DEPENDENT
          key: tendermint.block.tendermint_state_block_processing_time_count
          delay: '0'
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_state_block_processing_time_count
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: consensus
        -
          uuid: ffb59fe4492e46c3bfd7ad5d9176c202
          name: tendermint_state_block_processing_time_sum
          type: DEPENDENT
          key: tendermint.block.tendermint_state_block_processing_time_sum
          delay: '0'
          units: ms
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_state_block_processing_time_sum
                - value
                - ''
            -
              type: JAVASCRIPT
              parameters:
                - |
                  var send = parseFloat(value);
                  val = Math.floor(send);
                  return val;
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: consensus
        -
          uuid: 613debcc86bf4a49aebc0cebb526a858
          name: 'Fast sync status'
          type: DEPENDENT
          key: tendermint.fast.sync.status
          delay: '0'
          history: 30d
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_fast_syncing
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
        -
          uuid: 99aab85eb6d94915ba62d3856f88f7dc
          name: go_memstats_gc_sys_bytes
          type: DEPENDENT
          key: tendermint.go_memstats_gc_sys_bytes
          delay: '0'
          value_type: FLOAT
          units: B
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - go_memstats_gc_sys_bytes
                - function
                - sum
              error_handler: CUSTOM_VALUE
              error_handler_params: '0'
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: go
        -
          uuid: 92408e8140ce46b1a3a5bb5790e6ef68
          name: go_memstats_sys_bytes
          type: DEPENDENT
          key: tendermint.go_memstats_sys_bytes
          delay: '0'
          value_type: FLOAT
          units: B
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - go_memstats_sys_bytes
                - function
                - sum
              error_handler: CUSTOM_VALUE
              error_handler_params: '0'
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: go
        -
          uuid: 6ee69332e76f4bb1ab653d705e697dbe
          name: 'Last signed height'
          type: DEPENDENT
          key: tendermint.last.signed.height
          delay: '0'
          history: 1d
          trends: '0'
          status: DISABLED
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_validator_last_signed_height
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
        -
          uuid: a47cd7d5636341be8e6eb1b994c08347
          name: 'Number of TXs (in current block)'
          type: DEPENDENT
          key: tendermint.mempool.block_tx_count
          delay: '0'
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_consensus_num_txs
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: mempool
            -
              tag: Metric
              value: TXs
        -
          uuid: 0b83b1e6415048adbbc6c97b50331f61
          name: 'mempool Failed TXs Count (total)'
          type: DEPENDENT
          key: tendermint.mempool.failed_tx_count
          delay: '0'
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_mempool_failed_txs
                - value
                - ''
            -
              type: JAVASCRIPT
              parameters:
                - 'return parseFloat(value)'
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: mempool
        -
          uuid: ccc04b825403418ca75877ec7e5b85ca
          name: 'mempool TX count'
          type: DEPENDENT
          key: tendermint.mempool.size
          delay: '0'
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_mempool_size
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: mempool
        -
          uuid: 5f3caebd698349a698e8fb270e5e6976
          name: tendermint_mempool_tx_size_bytes_count
          type: DEPENDENT
          key: tendermint.mempool.tendermint_mempool_tx_size_bytes_count
          delay: '0'
          value_type: FLOAT
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_mempool_tx_size_bytes_count
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: mempool
        -
          uuid: 278aa442b6294c60832e600975bdf75c
          name: tendermint_mempool_tx_size_bytes_sum
          type: DEPENDENT
          key: tendermint.mempool.tendermint_mempool_tx_size_bytes_sum
          delay: '0'
          value_type: FLOAT
          units: B
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_mempool_tx_size_bytes_sum
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: mempool
        -
          uuid: ccf2178f9a0a41d3b20c6dd1eb2561f7
          name: 'Peer count'
          type: DEPENDENT
          key: tendermint.peer.count
          delay: '0'
          history: 30d
          preprocessing:
            -
              type: PROMETHEUS_PATTERN
              parameters:
                - tendermint_p2p_peers
                - value
                - ''
          master_item:
            key: prometheus.metrics.cometBFT
          tags:
            -
              tag: Application
              value: cometBFT
            -
              tag: Metric
              value: peers
      macros:
        -
          macro: '{$PROM_UPDATE_INTERVAL}'
          value: '14'
